---
title: "climater app"
resource_files:
- db_v3.rds
runtime: shiny
output: html_document
subtitle: v0.0.0.9010
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("shiny")
# install.packages("DT")
library(shiny)
options(shiny.suppressMissingContextError = TRUE)
library(DT)
if (basename(here::here()) == "climater") {
  devtools::load_all(here::here())
} else {
  library(climater)  
}

settings <- default_settings()
settings$output$show <- FALSE
#set_global_data_repo("repo_1", settings = settings)
set_global_data_repo("repo_2", settings = settings)

if (basename(here::here()) == "climater") {
  source(here::here("inst/app/04-load.R"))
} else {
  source("04-load.R")  
}
dat_db_0 <- data_read_db(vsn = "v3")
# dat_db_0 <- readRDS(here::here("inst/app/db_v3.Rds"))
```

## Inputs

```{r frontend, echo=FALSE}
dat_distance <- reactive({
  dat_geo <- data.frame(
    dim_latitude = ifelse(is.null(v <- input$geo_lat_auto), 1, v),
    dim_longitude = ifelse(is.null(v <- input$geo_long_auto), 1, v)
  )
  compute_geo_distance_v2(p_1 = dat_geo, p_2 = dat_station) %>%
    dplyr::pull(msr_distance) %>% round()
})
dist_measure <- "euclidean"
dist_measure_final <- dist_measure

# input_precip <- reactive({
#   prettyNum(seq(
#     from = min(dat_db_0$msr_precip_avg, na.rm = TRUE) %>% floor(),
#     to = max(dat_db_0$msr_precip_avg, na.rm = TRUE) %>% ceiling(),
#     by = 4), big.mark = ",")
# })

inputPanel(
  radioButtons("use_geo_auto", label = "Automatically detect location", 
    choices = c("yes", "no"), selected = "no", inline = TRUE),
  
  numericInput("geo_lat", label = "Your latitude (decimal sep: .)",
    value = 0, min = -90, max = 90),
  
  numericInput("geo_long", label = "Your longtiude (decimal sep: .)",
    value = 0, min = -180, max = 180)
)

inputPanel(
  sliderInput("msr_distance", label = "Max. distance to destination (km)",
    min = 0,
    max = 1000,
    value = 100, 
    step = 1,
    ticks = FALSE),
  
  selectInput("time_month", label = "Month of year",
    choices = 1:12, selected = 7),
  # sliderInput("time_month", label = "Month of year",
  #   min = 1, max = 12, value = 7, step = 1),
  
  sliderInput("msr_temp_min", label = "Min. temperature (°C)",
    min = min(dat_db_0$msr_temp_min, na.rm = TRUE) %>% floor(), 
    max = max(dat_db_0$msr_temp_min, na.rm = TRUE) %>% ceiling(), 
    value = mean(dat_db_0$msr_temp_min, na.rm = TRUE), 
    step = 0.5,
    ticks = FALSE),
  
  sliderInput("msr_temp_max", label = "Max. temperature (°C)",
    min = min(dat_db_0$msr_temp_max, na.rm = TRUE) %>% floor(),
    max = max(dat_db_0$msr_temp_max, na.rm = TRUE) %>% ceiling(), 
    value = mean(dat_db_0$msr_temp_min, na.rm = TRUE), 
    step = 0.5,
    ticks = FALSE),
  
  # sliderInput("msr_temp_avg", label = "Avg. temperature",
  #   min = min(dat_db_0$msr_temp_avg, na.rm = TRUE) %>% floor(),
  #   max = max(dat_db_0$msr_temp_avg, na.rm = TRUE) %>% ceiling(),
  #   value = mean(dat_db_0$msr_temp_avg, na.rm = TRUE),
  #   step = 0.5,
  #   ticks = FALSE),
  
  # sliderInput("msr_precip_min", label = "Min. precipitation",
  #   min = min(dat_db_0$msr_precip_min, na.rm = TRUE) %>% floor(),
  #   max = max(dat_db_0$msr_precip_min, na.rm = TRUE) %>% ceiling(),
  #   value = mean(dat_db_0$msr_precip_min, na.rm = TRUE), 
  #   step = 0.5,
  #   ticks = FALSE),
  #
  # sliderInput("msr_precip_max", label = "Max. precipitation",
  #   min = min(dat_db_0$msr_precip_max, na.rm = TRUE) %>% floor(),
  #   max = max(dat_db_0$msr_precip_max, na.rm = TRUE) %>% ceiling(),
  #   # value = mean(dat_db_0$msr_precip_min, na.rm = TRUE),
  #   value = 10,
  #   step = 0.5,
  #   ticks = FALSE),
  
  sliderInput("msr_precip_avg", label = "Rain days per month",
    min = min(dat_db_0$msr_precip_avg, na.rm = TRUE) %>% floor(),
    max = max(dat_db_0$msr_precip_avg, na.rm = TRUE) %>% ceiling(),
    value = 10, 
    step = 1,
    ticks = FALSE),
  
  # shinyWidgets::sliderTextInput("msr_precip_avg", label = "Rain days per month",
  #   choices = input_precip(),
  #   selected = 0, grid = TRUE),
  
  sliderInput("msr_sundur_avg", label = "Sunshine hours per day",
    min = min(dat_db_0$msr_sundur_avg, na.rm = TRUE) %>% floor(),
    max = max(dat_db_0$msr_sundur_avg, na.rm = TRUE) %>% ceiling(),
    value = mean(dat_db_0$msr_sundur_avg, na.rm = TRUE), 
    step = 1, 
    ticks = FALSE)
)

inputPanel(
  shiny::checkboxGroupInput("msr_inputs_chosen", label = "Choose inputs to use",
    choices = c(
      "Distance" = "msr_distance",
      # "Max. distance to destination" = "msr_distance",
      "Month" = "time_month",
      "Min. temperature" = "msr_temp_min",
      "Max. temperature" = "msr_temp_max",
      # "msr_temp_avg",
      # "msr_precip_min",
      # "msr_precip_max",
      "Rain days" = "msr_precip_avg",
      "Sunshine hours" = "msr_sundur_avg"
    ),
    selected = c("time_month", "msr_temp_avg")
  ),
  
  # shiny::selectInput("msr_inputs_chosen", label = "Choose inputs to use",
  #   choices = list(
  #     "Distance" = "msr_distance",
  #     # "Max. distance to destination" = "msr_distance",
  #     "Month" = "time_month",
  #     "Min. temperature" = "msr_temp_min",
  #     "Max. temperature" = "msr_temp_max",
  #     # "msr_temp_avg",
  #     # "msr_precip_min",
  #     # "msr_precip_max",
  #     "Rain days" = "msr_precip_avg",
  #     "Sunshine hours" = "msr_sundur_avg"
  #   ),
  #   selectize = TRUE,
  #   multiple = TRUE,
  #   selected = c("time_month", "msr_temp_avg")
  # ),
  
  selectInput("knn", label = "Number of recommendations",
    choices = 1:50, selected = 3),
  
  # selectInput("dist_measures", label = "Distance measures",
  #   choices = default_dist_measures(), selected = 1, multiple = TRUE),
  
  # selectInput("dist_measure_final", label = "Distance measures for ensemble",
  #   choices = default_dist_measures(), selected = 1),
  
  actionButton("do", "Submit", icon = icon("refresh")),
  
  # JS for automatic detection of geo location
  # Source: https://github.com/AugustT/shiny_geolocation
  tags$script('
      $(document).ready(function () {
        navigator.geolocation.getCurrentPosition(onSuccess, onError);

        function onError (err) {
          Shiny.onInputChange("geolocation", false);
        }

        function onSuccess (position) {
          setTimeout(function () {
            var coords = position.coords;
            console.log(coords.latitude + ", " + coords.longitude);
            Shiny.onInputChange("geolocation", true);
            Shiny.onInputChange("geo_lat_auto", coords.latitude);
            Shiny.onInputChange("geo_long_auto", coords.longitude);
          }, 1100)
        }
      });
              ')
)

observe({
  input$geo_lat_auto
  updateSliderInput(session, "msr_distance",
    value = round(mean(dat_distance(), na.rm = TRUE)),
    min=0,
    max=19000,
    step=500
#    min = min(dat_distance(), na.rm = TRUE),
#    max = max(dat_distance(), na.rm = TRUE),
#    step = 1
  )
})

dat_input_rea <- reactive({
  dat <- data.frame(
    dim_latitude = ifelse(input$use_geo_auto == "yes",
      ifelse(is.null(v <- input$geo_lat_auto), 0, as.numeric(v)),
      ifelse(is.null(v <- input$geo_lat), 0, as.numeric(v))
    ),
    dim_longitude = ifelse(input$use_geo_auto == "yes",
      ifelse(is.null(v <- input$geo_long_auto), 0, as.numeric(v)),
      ifelse(is.null(v <- input$geo_long), 0, as.numeric(v))
    ),
    time_month = as.numeric(input$time_month),
    msr_temp_min = as.numeric(input$msr_temp_min),
    msr_temp_max = as.numeric(input$msr_temp_max),
    # msr_temp_avg = as.numeric(input$msr_temp_avg),
    # msr_precip_min = as.numeric(input$msr_precip_min),
    # msr_precip_max = as.numeric(input$msr_precip_max),
    msr_precip_avg = as.numeric(input$msr_precip_avg),
    msr_sundur_avg = as.numeric(input$msr_sundur_avg),
    msr_distance = as.numeric(input$msr_distance)
  ) 
  
  msr_inputs_chosen <- input$msr_inputs_chosen
  print(msr_inputs_chosen)
  msr_inputs_chosen <- c("dim_latitude", "dim_longitude", msr_inputs_chosen)
  dat[ , msr_inputs_chosen]
})

dat_output_rea <- eventReactive(input$do, {
  dat_input <- dat_input_rea()
  knn <- as.numeric(input$knn)
  dist_measures <- input$dist_measures
  dist_measure_final <- input$dist_measure_final
  
  if (basename(here::here()) == "climater") {
    source(here::here("inst/app/06-model.R"), local = TRUE)
  } else {
    source("6-model.R", local = TRUE)
  }
  
  model_result_gathered
})
```

## Outputs {.tabset}

### Recommendations

```{r echo=FALSE}
renderDataTable({
  this <- dat_output_rea()$prediction %>%  
    dat_transform_relevant_columns() %>% 
    dplyr::mutate(msr_distance = msr_distance %>% round(4)) %>% 
    dat_transform_names_to_label()
  
}, options = list(scrollX = TRUE))
# TODO-20180705: encapsulate column selection in own function to be more
# flexible and make code easier to maintain
```

### Input

```{r echo=FALSE}
renderDataTable({
  dat_output_rea()$input %>% 
    dat_transform_names_to_label()
}, options = list(scrollX = TRUE))

```

### Geo location

#### Latitude

Auto detect:

```{r output-lat-auto, echo = FALSE}
renderPrint({
  input$geo_lat_auto
})
```

User defined:

```{r output-lat, echo = FALSE}
renderPrint({
  input$geo_lat
})
```


#### Longitude

Auto detect:

```{r output-long-auto, echo = FALSE}
renderPrint({
  input$geo_long_auto
})
```

User defined:

```{r output-long, echo = FALSE}
renderPrint({
  input$geo_long
})
```

#### Geo location

```{r output-geoloc, echo = FALSE}
renderPrint({
  input$geolocation
})
```

#### Distances (summary)

```{r output-dists, echo = FALSE}
renderPrint({
  dat_distance() %>% summary()
})
```
